/**
 * Modèles soumis à l'isolation multi-tenant : modèle → colonne portant l'identifiant d'entreprise.
 *
 * RÈGLE : tout nouveau modèle ayant un champ `companyId` DOIT être ajouté ici ET recevoir
 * `SELECT afg_enable_rls('"Modele"')` dans sa migration. Les tests
 * (tests/integration/rls-coverage.test.ts) échouent sinon.
 */
export const TENANT_KEY: Readonly<Record<string, "companyId" | "id">> = {
  Company: "id",
  CompanyMembership: "companyId",
  Invitation: "companyId",
  Role: "companyId",
  RolePermission: "companyId",
  Subscription: "companyId",
  CompanyModule: "companyId",
  UsageLimit: "companyId",
  Branch: "companyId",
  Site: "companyId",
  Department: "companyId",
  CostCenter: "companyId",
  Notification: "companyId",
  NotificationPreference: "companyId",
  AuditLog: "companyId",
  Tax: "companyId",
  NumberSequence: "companyId",
  NumberingConfig: "companyId",
  Customer: "companyId",
  Contact: "companyId",
  Lead: "companyId",
  PipelineStage: "companyId",
  Opportunity: "companyId",
  Activity: "companyId",
  ProductCategory: "companyId",
  Product: "companyId",
  Warehouse: "companyId",
  StockLevel: "companyId",
  StockMovement: "companyId",
  Quote: "companyId",
  QuoteLine: "companyId",
  SalesOrder: "companyId",
  OrderLine: "companyId",
  Delivery: "companyId",
  DeliveryLine: "companyId",
  Invoice: "companyId",
  InvoiceLine: "companyId",
  InvoiceInstallment: "companyId",
  CreditNote: "companyId",
  CreditNoteLine: "companyId",
  Payment: "companyId",
  Reminder: "companyId",
  Supplier: "companyId",
  PurchaseRequest: "companyId",
  PurchaseRequestLine: "companyId",
  PurchaseOrder: "companyId",
  PurchaseOrderLine: "companyId",
  GoodsReceipt: "companyId",
  GoodsReceiptLine: "companyId",
  SupplierBill: "companyId",
  SupplierBillLine: "companyId",
  ApprovalPolicy: "companyId",
  ApprovalRequest: "companyId",
  ApprovalRule: "companyId",
  ImportJob: "companyId",
  Vehicle: "companyId",
  Driver: "companyId",
  VehicleAssignment: "companyId",
  Trip: "companyId",
  FuelLog: "companyId",
  MaintenanceRecord: "companyId",
  VehicleCompliance: "companyId",
  TrafficFine: "companyId",
  ConstructionSite: "companyId",
  SiteBudgetLine: "companyId",
  SiteMember: "companyId",
  SiteEquipment: "companyId",
  SiteMaterialPlan: "companyId",
  SiteMaterialIssue: "companyId",
  SiteSubcontract: "companyId",
  SiteReport: "companyId",
  ApprovalRuleStep: "companyId",
  ApprovalDecision: "companyId",
  FiscalYear: "companyId",
  AccountingPeriod: "companyId",
  Journal: "companyId",
  LedgerAccount: "companyId",
  AccountMapping: "companyId",
  JournalEntry: "companyId",
  JournalLine: "companyId",
  DashboardPreference: "companyId",
  Employee: "companyId",
  EmploymentContract: "companyId",
  LeaveType: "companyId",
  LeaveRequest: "companyId",
  Attendance: "companyId",
  Evaluation: "companyId",
  Training: "companyId",
  PayrollItem: "companyId",
  EmployeePayrollItem: "companyId",
  PayrollRun: "companyId",
  Payslip: "companyId",
  PayslipLine: "companyId",
  Project: "companyId",
  ProjectTask: "companyId",
  TimeEntry: "companyId",
  DocFolder: "companyId",
  Document: "companyId",
  DocumentVersion: "companyId",
  DocumentLink: "companyId",
  DocumentShare: "companyId",
  FinanceAccount: "companyId",
  FinanceCategory: "companyId",
  FinancialTransaction: "companyId",
  Expense: "companyId",
  Budget: "companyId",
};

export const TENANT_MODELS = Object.keys(TENANT_KEY);
